// Типи ППО та кольори відображення

export const pvoTypes = [
  {
    name: 'Кулемет',
    price: 400,
    radius: 100,
    damage: 14,
    cd: 400,
    img: 'assets/kulemet.png',
    iconSize: [40, 40],
    canTarget: { drones: true, rockets: false },
  },
  {
    name: 'С-300',
    price: 1100,
    radius: 150,
    damage: 27,
    cd: 850,
    img: 'assets/c300.png',
    iconSize: [50, 33],
    canTarget: { drones: true, rockets: true },
  },
  {
    name: 'Кільчень',
    price: 1800,
    radius: 175,
    damage: 38,
    cd: 925,
    img: 'assets/kilchen.png',
    iconSize: [55, 37],
    canTarget: { drones: true, rockets: false },
  },
  {
    name: 'Patriot',
    price: 2400,
    radius: 200,
    damage: 50,
    cd: 1100,
    img: 'assets/patriot.png',
    iconSize: [55, 55],
    canTarget: { drones: false, rockets: true },
  },
  {
    name: 'F-16',
    price: 3600,
    radius: 210,
    damage: 300,
    cd: 800,
    img: 'assets/f16.png',
    mobile: true,
    noUpgrade: true,
    iconSize: [55, 55],
    canTarget: { drones: true, rockets: true },
  },
  {
    name: 'РЕБ',
    price: 500,
    radius: 190,
    damage: 0,
    cd: 0,
    reb: true,
    slowFactor: 0.6,
    img: 'assets/reb.png',
    iconSize: [35, 35],
    canTarget: { drones: false, rockets: false },
  },
  {
    name: 'Аеропорт',
    price: 3000,
    radius: 200,
    damage: 0,
    cd: 0,
    img: 'assets/aeroport.png',
    noUpgrade: true,
    iconSize: [55, 55],
    canTarget: { drones: false, rockets: false },
  },
];

export const pvoColorMap = {
  Кулемет: '#52f752',
  'С-300': '#30c730',
  Кільчень: '#ffb855ff',
  Patriot: '#228B22',
  РЕБ: '#d673fa',
  'F-16': '#1f8cff',
  Аеропорт: '#1f8cff',
};
